#!/bin/sh
# 
# vpnserver	This shell script takes care of starting and stopping
#		SoftEther VPN server.
# 
# chkconfig: 2345 99 01
# description: SoftEther VPN server.

DAEMON=/usr/vpnserver/vpnserver
LOCK=/var/lock/subsys/vpnserver

test -x $DAEMON || exit 0

case "$1" in
	start)
		$DAEMON start
		touch $LOCK
	;;
	stop)
		$DAEMON stop
		rm $LOCK
	;;
	restart)
		$DAEMON stop
		sleep 3
		$DAEMON start
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
